### ISSUE TITLE
Summarizer summarizes always twice

### ISSUE THREAD

**Issue by eigenstil** [beeper/widget-summarizer#1]
this is very annoying, when summarizer summarizes a lot of messages, e.g. 30+. Because then it will be very hard to identify where the duplicate starts ;-)

Screenshot here:
![image](https://github.com/beeper/widget-summarizer/assets/37832701/d4b1e220-40ca-44ec-b4c1-059b06d622a2)

**Comment by griffinli** [comment]
Should be fixed now! Let me know if it's still happening

**Comment by eigenstil** [comment]
fixed! 👍🎉
