### ISSUE TITLE
No option to choose how many messages are summarized once an answer is provided

### ISSUE THREAD

**Issue by jackmawer** [beeper/widget-summarizer#2]
Summarizer does not give an option to change how many messages are summarized once it has already provided a response.

**Comment by griffinli** [comment]
Yup - that's supposed to happen. You can just exit out of the widget and re-open it to summarize again.

**Comment by jackmawer** [comment]
@griffinli Sorry, I should have been more specific in my original post - I've found that closing and re-opening the widget just seems to re-trigger the same response. It might be worth having just a button to switch back to the initial screen to choose the time period to summarize.
